In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
path = '/Users/sinsakuokazaki/Project/pred-future-sales/\
input/competitive-data-science-predict-future-sales/'

In [2]:
sales_train = pd.read_csv('/Users/sinsakuokazaki/Project/pred-future-sales/\
input/competitive-data-science-predict-future-sales/sales_train.csv')

train = pd.read_csv('/Users/sinsakuokazaki/Project/pred-future-sales/\
input/competitive-data-science-predict-future-sales/train.csv')

test = pd.read_csv('/Users/sinsakuokazaki/Project/pred-future-sales/\
input/competitive-data-science-predict-future-sales/test.csv')

item_categories = pd.read_csv('/Users/sinsakuokazaki/Project/pred-future-sales/\
input/competitive-data-science-predict-future-sales/item_categories.csv')

items = pd.read_csv('/Users/sinsakuokazaki/Project/pred-future-sales/\
input/competitive-data-science-predict-future-sales/items.csv')

shops = pd.read_csv('/Users/sinsakuokazaki/Project/pred-future-sales/\
input/competitive-data-science-predict-future-sales/shops.csv')

In [3]:
sales_train.head()

,date,date_block_num,shop_id,item_id,item_price,item_cnt_day,dayofweek,dayofmonth,month,quarter,year,minute,hour,total_sales,shop_name,item_name,item_category_id,item_category_name
0,2013-01-02,0,59,22154,999.00,1.0,2,2,1,1,2013,0,0,999.00,"Ярославль ТЦ ""Альтаир""",ЯВЛЕНИЕ 2012 (BD),37,Кино - Blu-Ray
1,2013-01-03,0,25,2552,899.00,1.0,3,3,1,1,2013,0,0,899.00,"Москва ТРК ""Атриум""",DEEP PURPLE The House Of Blue Light LP,58,Музыка - Винил
2,2013-01-05,0,25,2552,899.00,-1.0,5,5,1,1,2013,0,0,-899.00,"Москва ТРК ""Атриум""",DEEP PURPLE The House Of Blue Light LP,58,Музыка - Винил
3,2013-01-06,0,25,2554,1709.05,1.0,6,6,1,1,2013,0,0,1709.05,"Москва ТРК ""Атриум""",DEEP PURPLE Who Do You Think We Are LP,58,Музыка - Винил
4,2013-01-15,0,25,2555,1099.00,1.0,1,15,1,1,2013,0,0,1099.00,"Москва ТРК ""Атриум""",DEEP PURPLE 30 Very Best Of 2CD (Фирм.),56,Музыка - CD фирменного производства

In [4]:
train.head()

,date_block_num,item_id,shop_id,item_cnt_day,total_sales,item_name,item_category_id,shop_name,month,year,quarter,item_category_name
0,0,19,25,1.0,28.0,/ЗОЛОТАЯ КОЛЛЕКЦИЯ м/ф-72,40,"Москва ТРК ""Атриум""",1,2013,1,Кино - DVD
1,0,27,1,1.0,1890.0,"007 Legends [PS3, русская версия]",19,"!Якутск ТЦ ""Центральный"" фран",1,2013,1,Игры - PS3
2,0,27,2,1.0,2499.0,"007 Legends [PS3, русская версия]",19,"Адыгея ТЦ ""Мега""",1,2013,1,Игры - PS3
3,0,27,10,1.0,1890.0,"007 Legends [PS3, русская версия]",19,Жуковский ул. Чкалова 39м?,1,2013,1,Игры - PS3
4,0,27,19,1.0,2499.0,"007 Legends [PS3, русская версия]",19,"Курск ТЦ ""Пушкинский""",1,2013,1,Игры - PS3

In [5]:
test.head()

,Unnamed: 0,ID,shop_id,item_id,item_name,item_category_id,item_category_name,shop_name,combination_id,in_train,month,year,quarter,date_block_num
0,0,0,5,5037,"NHL 15 [PS3, русские субтитры]",19,Игры - PS3,"Вологда ТРЦ ""Мармелад""","(5, 5037)",True,11,2015,4,34
1,1,1,5,5320,ONE DIRECTION Made In The A.M.,55,Музыка - CD локального производства,"Вологда ТРЦ ""Мармелад""","(5, 5320)",False,11,2015,4,34
2,2,2,5,5233,"Need for Speed Rivals (Essentials) [PS3, русск...",19,Игры - PS3,"Вологда ТРЦ ""Мармелад""","(5, 5233)",True,11,2015,4,34
3,3,3,5,5232,"Need for Speed Rivals (Classics) [Xbox 360, ру...",23,Игры - XBOX 360,"Вологда ТРЦ ""Мармелад""","(5, 5232)",True,11,2015,4,34
4,4,4,5,5268,"Need for Speed [PS4, русская версия]",20,Игры - PS4,"Вологда ТРЦ ""Мармелад""","(5, 5268)",False,11,2015,4,34

In [10]:
shop_ids = np.sort(sales_train['shop_id'].unique())
for i in shop_ids:
    item_data = sales_train[sales_train['shop_id'] == i].sort_values("date_block_num")
    file_path = path + "shop-" + str(i) +".csv"
    item_data.to_csv(file_path, index = False)

In [ ]:
shop_ids = np.sort(test)